Repository VulpixGlow/glowintheblue, pull requests merged in 2021-05, with the labels that each got.

#2 Test background
  App.js
  assets/seahorse.jpg
Labels: Test

#6 feat: category pop out screen
  package-lock.json
  package.json
  src/firebase/config.js
  src/screens/HomeScreen/HomeScreen.js
  src/screens/HomeScreen/styles.js
  yarn.lock
Labels: enhancement

#12 Graph examples for displaying data
  package.json
  src/screens/GraphScreen/GraphScreen.js
  yarn.lock
Labels: enhancement

#13 Update .gitignore file
  .gitignore
Labels: enhancement

#16 Dev branch stable
  .gitignore
  package-lock.json
  package.json
  src/Success/Success.js
  src/Success/party.jpeg
  src/screens/GraphScreen/GraphScreen.js
  src/screens/HomeScreen/HomeScreen.js
  src/screens/TimeScreen/PomodoroTimer.js
  yarn.lock
Labels: enhancement

#21 Points srceen
  App.js
  src/screens/HomeScreen/styles.js
  src/screens/PointScreen/PointScreen.js
  src/screens/TimerExperiment/TimerExperiment.js
Labels: bug

#23 Login logic
  App.js
  src/screens/FooterScreen/FooterScreen.js
  src/screens/HomeScreen/HomeScreen.js
  src/screens/Onboarding/Onboarding.js
  src/screens/PointScreen/PointScreen.js
  src/screens/Points/Points.js
  src/screens/StoreScreen/StoreScreen.js
  src/screens/Tabs/Tabs.js
  src/screens/TimeScreen/PomodoroTimer.js
  src/screens/TimeScreen/Timer.js
  src/screens/TimeScreen/TimerButtons.js
  src/screens/TimeScreen/TimerDisplay.js
  src/screens/TimeScreen/TimerHeader.js
  src/screens/TimerExperiment/TimerExperiment.js
  src/screens/index.js
Labels: enhancement

#28 Points storage
  App.js
  README.md
  package-lock.json
  package.json
  src/screens/HomeScreen/HomeScreen.js
  src/screens/TimerExperiment/TimerExperiment.js
Labels: enhancement

#29 Dev branch stable
  App.js
  README.md
  Slides.js
  config/Firebase.js
  package-lock.json
  package.json
  src/Success/Success.js
  src/screens/CategoryScreen/CategoryScreen.js
  src/screens/CategoryScreen/styles.js
  src/screens/CountDown/CountDown.js
  src/screens/FooterScreen/FooterScreen.js
  src/screens/GraphScreen/GraphScreen.js
  src/screens/HomeScreen/HomeScreen.js
  src/screens/HomeScreen/styles.js
  src/screens/LoginScreen/LoginScreen.js
  src/screens/Onboarding/Onboarding.js
  src/screens/Onboarding/components/Footer.js
  src/screens/Onboarding/components/Page.js
  src/screens/Onboarding/components/RoundedButton.js
  src/screens/PointScreen/PointScreen.js
  src/screens/SideMenu/SideMenu.js
  src/screens/StackNav/StackNav.js
  src/screens/StoreScreen/StoreScreen.js
  src/screens/Success/Success.js
  src/screens/Success/party.jpeg
  src/screens/TimeScreen/PomodoroTimer.js
  src/screens/TimeScreen/Timer.js
  src/screens/TimeScreen/TimerButtons.js
  src/screens/TimeScreen/TimerDisplay.js
  src/screens/TimeScreen/TimerHeader.js
  src/screens/TimerExperiment/TimerExperiment.js
  src/screens/TimerExperiment/styles.js
  src/screens/TimerScreen/TimerScreen.js
  src/screens/index.js
  yarn.lock
Labels: enhancement

#31 feat: add category dropdown and add style changes to TimerExperiment
  .vscode/settings.json
  package-lock.json
  package.json
  src/screens/TimerExperiment/SelectDropdownComponent.js
  src/screens/TimerExperiment/TimerExperiment.js
  src/screens/TimerExperiment/styles.js
  yarn.lock
Labels: enhancement

#34 Mon
  .vscode/settings.json
  src/screens/GraphScreen/GraphScreen.js
  src/screens/PointScreen/PointScreen.js
  src/screens/StoreScreen/StoreScreen.js
Labels: enhancement

#35 Fix points
  package-lock.json
  package.json
  src/screens/PointScreen/PointScreen.js
  src/screens/TimerExperiment/TimerExperiment.js
  src/screens/TimerExperiment/styles.js
Labels: bug

#41 Chumi/wednes
  package-lock.json
  src/screens/InviteScreen/InviteScreen.js
  src/screens/TimerExperiment/TimerExperiment.js
  yarn.lock
Labels: enhancement

#42 Bar graph eb
  App.js
  package-lock.json
  package.json
  src/screens/CountDown/CountDown.js
  src/screens/FooterScreen/FooterScreen.js
  src/screens/GraphScreen/GraphScreen.js
  src/screens/GraphScreen/GraphScreenErrors.js
  src/screens/GraphScreen/GraphScreenVistory.js
  src/screens/HomeScreen/HomeScreen.js
  src/screens/PointScreen/PointScreen.js
  src/screens/StoreScreen/StoreScreen.js
  src/screens/Success/Success.js
  src/screens/TimerExperiment/SelectDropdownComponent.js
  src/screens/TimerExperiment/TimerExperiment.js
  src/screens/TimerExperiment/filterDataFunction.js
  src/screens/TimerExperiment/filterDataPieFunction.js
Labels: enhancement

#49 Bar graph eb
  App.js
  app.json
  assets/images/chart-bar-solid.svg
  assets/seahorse.jpg
  src/screens/GraphScreen/GraphScreen.js
  src/screens/GraphScreen/GraphScreenErrors.js
  src/screens/GraphScreen/GraphScreenVistory.js
  src/screens/GraphScreen/styles.js
  src/screens/HomeScreen/HomeScreen.js
  src/screens/Onboarding/Onboarding.js
  src/screens/PieChartScreen/PieChartScreen.js
  src/screens/StackNav/StackNav.js
  src/screens/TimerExperiment/SelectDropdownComponent.js
  src/screens/TimerExperiment/TimerExperiment.js
  src/screens/TimerExperiment/filterDataFunction.js
  src/screens/TimerExperiment/filterDataPieFunction.js
  src/screens/TimerScreen/TimerScreen.js
  src/screens/index.js
Labels: enhancement

#55 chore: refactor code to reflect context provider
  App.js
  UserContext.js
  src/screens/CategoryScreen/CategoryScreen.js
  src/screens/CategoryScreen/styles.js
  src/screens/FooterScreen/FooterScreen.js
  src/screens/GraphScreen/GraphScreen.js
  src/screens/GroupScreen/GroupScreen.js
  src/screens/GroupsScreen/GroupsScreen.js
  src/screens/HomeScreen/HomeScreen.js
  src/screens/InviteScreen/InviteScreen.js
  src/screens/LoginScreen/LoginScreen.js
  src/screens/NotifScreen/NotifScreen.js
  src/screens/PieChartScreen/PieChartScreen.js
  src/screens/PointScreen/PointScreen.js
  src/screens/Success/Success.js
  src/screens/Success/party.jpeg
  src/screens/TimerExperiment/TimerExperiment.js
Labels: bug

#57 fix: remove bugs, refactor code, fix api/sessions/update route
  App.js
  UserContext.js
  package-lock.json
  package.json
  src/screens/BottomTabs/BottomTabs.js
  src/screens/CategoryScreen/CategoryScreen.js
  src/screens/CategoryScreen/styles.js
  src/screens/FooterScreen/FooterScreen.js
  src/screens/GraphScreen/GraphScreen.js
  src/screens/GraphScreen/filterDataFunction.js
  src/screens/GroupScreen/GroupScreen.js
  src/screens/GroupsScreen/GroupsScreen.js
  src/screens/HomeScreen/HomeScreen.js
  src/screens/InviteScreen/InviteScreen.js
  src/screens/LoginScreen/LoginScreen.js
  src/screens/NotifScreen/NotifScreen.js
  src/screens/PieChartScreen/PieChartScreen.js
  src/screens/PointScreen/PointScreen.js
  src/screens/RegistrationScreen/RegistrationScreen.js
  src/screens/Success/Success.js
  src/screens/Success/party.jpeg
  src/screens/TimerExperiment/TimerExperiment.js
  src/screens/index.js
Labels: enhancement

#64 fix: provide a default timer value so timer doesn't reset to zero
  src/screens/GraphScreen/GraphScreen.js
  src/screens/TimerExperiment/TimerExperiment.js
Labels: enhancement

#67 Timeline design
  App.js
  package-lock.json
  src/dataFunctions/FilterDataBarGraph.js
  src/dataFunctions/FilterDataFunction.js
  src/dataFunctions/FilterDataPieFunction.js
  src/screens/BarGraphScreen/BarGraphScreen.js
  src/screens/BarGraphScreen/GraphScreenErrors.js
  src/screens/BarGraphScreen/GraphScreenVistory.js
  src/screens/BottomTabs/BottomTabs.js
  src/screens/FooterScreen/FooterScreen.js
  src/screens/HomeScreen/HomeScreen.js
  src/screens/PieChartScreen/PieChartScreen.js
  src/screens/PieChartScreen/styles.js
  src/screens/TimelineScreen/TimelineScreen.js
  src/screens/TimelineScreen/styles.js
  src/screens/TimerExperiment/TimerExperiment.js
  src/screens/TimerExperiment/styles.js
  src/screens/index.js
Labels: enhancement

#71 fix: refactored code in multiple files
  App.js
  assets/images/hiw-seahorse.png
  assets/images/main-splash.png
  src/screens/BottomTabs/BottomTabs.js
  src/screens/GroupsScreen/GroupsScreen.js
  src/screens/InviteScreen/InviteScreen.js
  src/screens/NotifScreen/NotifScreen.js
  src/screens/TimerExperiment/TimerExperiment.js
Labels: enhancement

#72 Update README.md
  README.md
Labels: documentation

#73 feat: combine group screen with invite screen
  src/screens/GroupsScreen/GroupsScreen.js
  src/screens/InviteScreen/InviteScreen.js
Labels: enhancement

#75 fix: display totalpoints for user
  App.js
  src/screens/TimelineScreen/TimelineScreen.js
  src/screens/TimerExperiment/TimerExperiment.js
Labels: bug

#77 fix: timer display for seconds
  src/screens/TimerExperiment/TimerExperiment.js
Labels: enhancement

#78 Update README.md
  README.md
Labels: documentation

#81 update README.md
  README.md
  src/screens/TimerExperiment/TimerExperiment.js
Labels: documentation

#80 Monday/shann
  App.js
  package-lock.json
  package.json
  src/screens/BottomTabs/BottomTabs.js
  src/screens/GroupScreen/GroupScreen.js
  src/screens/GroupsScreen/GroupsScreen.js
  src/screens/HomeScreen/HomeScreen.js
  src/screens/InviteScreen/InviteScreen.js
  src/screens/NotifScreen/NotifScreen.js
Labels: enhancement

#82 fix: resolve typos and add accessibility labels
  App.js
  package-lock.json
  package.json
  src/dataFunctions/FilterDataFunction.js
  src/screens/Onboarding/Onboarding.js
  src/screens/PieChartScreen/PieChartScreen.js
  src/screens/TimerExperiment/TimerExperiment.js
  src/screens/TimerExperiment/styles.js
Labels: documentation

#83 fix: resolve syntax errors
  src/screens/GroupsScreen/GroupsScreen.js
  src/screens/NotifScreen/NotifScreen.js
  src/screens/PieChartScreen/PieChartScreen.js
Labels: bug

#84 Han mon
  package-lock.json
  src/screens/TimerExperiment/TimerExperiment.js
  yarn.lock
Labels: bug, enhancement

#85 Han mon
  src/screens/TimerExperiment/TimerExperiment.js
Labels: enhancement

#94 Bennett elisa patch 4
  README.md
  assets/images/hiw-octopus.png
  assets/images/hiw-seahorse.png
  assets/images/hiw-squid.png
  assets/images/main-splash.png
  package-lock.json
  src/screens/GroupsScreen/GroupsScreen.js
  src/screens/NotifScreen/NotifScreen.js
  src/screens/PieChartScreen/PieChartScreen.js
  src/screens/TimerExperiment/TimerExperiment.js
  src/screens/TimerExperiment/styles.js
  yarn.lock
Labels: documentation
